import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.76.1';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { projectId } = await req.json();
    
    if (!projectId) {
      return new Response(JSON.stringify({ error: 'Project ID is required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Fetch project data with blocks and works
    const { data: blocks, error: blocksError } = await supabase
      .from('project_blocks')
      .select('*, project_works(*)')
      .eq('project_id', projectId)
      .order('order_index');

    if (blocksError) {
      console.error('Error fetching blocks:', blocksError);
      throw blocksError;
    }

    if (!blocks || blocks.length === 0) {
      return new Response(JSON.stringify({ error: 'No blocks found for project' }), {
        status: 404,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Prepare work items for AI
    const workItems = blocks.flatMap(block => 
      block.project_works.map((work: any) => ({
        blockName: block.name,
        name: work.name,
        description: work.description,
        quantity: work.quantity,
        unitType: work.unit_type,
      }))
    );

    // Call Lovable AI to generate timeline
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not configured');
    }

    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          {
            role: 'system',
            content: `You are a construction project planning expert. Generate a preliminary timeline for renovation work items. Consider logical dependencies (e.g., demolition before construction, electrical before drywall, etc.). Return a JSON array with this structure:
[
  {
    "phase": 1,
    "workName": "Work item name",
    "durationDays": 7
  }
]
Organize work items in logical construction sequence with phase numbers (1, 2, 3, etc.) indicating the order of execution. Duration should be a number in days.`
          },
          {
            role: 'user',
            content: `Generate a construction timeline for these work items:\n${JSON.stringify(workItems, null, 2)}`
          }
        ],
        tools: [
          {
            type: 'function',
            function: {
              name: 'generate_timeline',
              description: 'Generate construction timeline with phases and dependencies',
              parameters: {
                type: 'object',
                properties: {
                  timeline: {
                    type: 'array',
                    items: {
                      type: 'object',
                      properties: {
                        phase: { type: 'number' },
                        workName: { type: 'string' },
                        durationDays: { type: 'number' }
                      },
                      required: ['phase', 'workName', 'durationDays'],
                      additionalProperties: false
                    }
                  }
                },
                required: ['timeline'],
                additionalProperties: false
              }
            }
          }
        ],
        tool_choice: { type: 'function', function: { name: 'generate_timeline' } }
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('AI Gateway error:', aiResponse.status, errorText);
      
      if (aiResponse.status === 429) {
        throw new Error('Rate limit exceeded. Please try again later.');
      }
      if (aiResponse.status === 402) {
        throw new Error('Payment required. Please add credits to your workspace.');
      }
      
      throw new Error('Failed to generate timeline');
    }

    const aiData = await aiResponse.json();
    const toolCall = aiData.choices[0]?.message?.tool_calls?.[0];
    
    if (!toolCall) {
      throw new Error('No timeline generated by AI');
    }

    const timeline = JSON.parse(toolCall.function.arguments).timeline;

    // Update project with generated timeline
    const { error: updateError } = await supabase
      .from('projects')
      .update({ preliminary_timeline: timeline })
      .eq('id', projectId);

    if (updateError) {
      console.error('Error updating project:', updateError);
      throw updateError;
    }

    console.log('Timeline generated successfully for project:', projectId);

    return new Response(JSON.stringify({ success: true, timeline }), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error) {
    console.error('Error in generate-timeline function:', error);
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
